spring:
  application:
    name: orders

server:
  port: ${order.port:8091}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka02:8762/eureka
  instance:
    hostname: eureka02
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

ribbon:
 ConnectTimeout: 1000
 ReadTimeout: 10000
 SocketTimeout: 1000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
      circuitBreaker:
        requestVolumeThreshold: 2
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 3000


