spring:
  application:
    name: orders

server:
  port: ${orders.port:8091}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka02:8762/eureka
  instance:
    hostname: eureka02
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

ribbon:
 ConnectTimeout: 1000
 ReadTimeout: 1000
 SocketTimeout: 1000

hystrix:
  command:
    circuitBreaker:
      requestVolumeThreshold: 2


